site_name: Kotlin for FRC
site_url: https://kotlin-for-frc.github.io/

extra_css:
  - stylesheets/extra.css
  
nav:
  - Home:
    - home.md
  - Getting Started:
    - getting-started.md
    - Migration Guide: migrating.md

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom